version: '3.9'
services:
  pedagang:
    build: ./pedagang
    ports:
      - "8482:8482"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-cloud-config.json
      - HTTP_PORT=8482
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - WEB_URL=https://localhot:3000
      - TZ=Asia/Jakarta
      - AUTH_URL=https://auth.jajan-yuk.pegelinux.my.id
    volumes:
      - ./config/google-cloud-config.json:/app/google-cloud-config.json
      - ./images:/app/images
    depends_on:
      - redis

  user:
    build: ./user
    ports:
      - "8481:8481"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-cloud-config.json
      - HTTP_PORT=8481
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - WEB_URL=https://localhot:3000
      - TZ=Asia/Jakarta
    volumes:
      - ./config/google-cloud-config.json:/app/google-cloud-config.json
    depends_on:
      - redis

  email:
    build: ./email
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-cloud-config.json
      - SMTP_PASS=password
    volumes:
      - ./config/google-cloud-config.json:/app/google-cloud-config.json

  auth:
    build: ./auth
    ports:
      - "8480:8480"
    environment:
      - HTTP_PORT=8480
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis-jajan-yuk:/data

volumes:
  redis-jajan-yuk:
    driver: local