version: '3.9'
services:
  email:
    build: ./email

  auth:
    build: ./auth
    ports:
      - "8480:8480"
    environment:
      - HTTP_PORT=8480
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-jajan-yuk:/data

volumes:
  redis-jajan-yuk:
    driver: local