version: '3.9'
services:
  email:
    build: ./email
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-cloud-config.json
    volumes:
      - ./config/google-cloud-config.json:/app/google-cloud-config.json

  auth:
    build: ./auth
    ports:
      - "8480:8480"
    environment:
      - HTTP_PORT=8480
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis-jajan-yuk:/data

volumes:
  redis-jajan-yuk:
    driver: local